name: bump-version-with-renovate

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      dryrun:
        description: Perform a dry run by logging messages instead of creating/updating/deleting branches and PRs.
        required: true
        type: boolean
        default: true
  schedule:
    # https://crontab.guru/
    - cron: '0 4 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    # if: github.repository == 'ivankatliarchuk/.github'
    steps:
      # https://github.com/renovatebot/github-action
      - name: checkout
        uses: actions/checkout@v4.2.2
      # https://github.com/renovatebot/github-action
      - name: self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          # docker-cmd-file: .github/renovate-entrypoint.sh
          # docker-user: root
          # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: example/renovate-config.js